---
title: "Developing Data Product week 2 Project"
author: "Shivesh Rja Sahu"
date: "October 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## My First Leaflet Map
Create a leaflet map object.
```{r cars}
library(leaflet)
map <- leaflet() %>% addTiles()
```

Create a marker with a picture of MIT and a link to its homepage.
```{r}
Icon <- makeIcon(
   iconUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi1.wp.com%2Fedupadhai.com%2Fwp-content%2Fuploads%2F2016%2F08%2FManipal-University-ranks-first-among-non-government-universities-in-India.jpg%3Ffit%3D600%252C400%26ssl%3D1&imgrefurl=https%3A%2F%2Fedupadhai.com%2Fmanipal-university%2F&tbnid=r-qm4exI4_AHsM&vet=12ahUKEwj0yOzEypblAhVm53MBHQYeDmwQMygGegUIARD4AQ..i&docid=y0ook43YNh5ZHM&w=600&h=400&q=manipal%20institute%20of%20technology%20manipal&ved=2ahUKEwj0yOzEypblAhVm53MBHQYeDmwQMygGegUIARD4AQ",
   iconWidth = 30*408/255, iconHeight = 30,
   iconAnchorX = 30*408/255/2, iconAnchorY = 30/2
)
```

Add the marker to the map and display the map.
```{r}

map %>%
   addTiles() %>% 
   addMarkers(lat=13.3490, lng=74.7856)
```